[package]
name = "cs3211_assignment_3"
version = "0.1.1"
edition = "2024"

[dependencies]
rand = "0.9.0"
rand_chacha = "0.9.0"
rand_xoshiro = "0.7.0"
tokio = { version = "1.44.1", features = ["full"] }